### ISSUE TITLE
It seems like Java 8 is required

### ISSUE THREAD

**Issue by novakboskov** [Engelberg/ubergraph#13]
In Java <= 7 there is no constructor `PriorityQueue(Comparator<? super E> comparator)` which corresponds with `(PriorityQueue. (fn [x y] (compare (x 0) (y 0))))`, it is introduced in Java 8. You use that constructor in `alg/least-cost-path-with-heuristic` and `alg/least-cost-path` (since v0.1.2 as far as I can see) and it raise error for Java <= 7. 
Maybe it should be mentioned somewhere in README?

**Comment by Engelberg** [comment]
Thanks for pointing that out.  I will add it to the README along with some
other clarifications soon, probably next weekend.

**Comment by Engelberg** [comment]
README updated and will be visible in version 0.2.0 which I am pushing soon.
