### ISSUE TITLE
Self-cycles silently ignored

### ISSUE THREAD

**Issue by alanlcode** [Engelberg/ubergraph#15]
Version: 0.1.9
Commit: c525a374

Erroneous Behavior:  The following graph should have one node and one edge (from the node back to itself), but in fact has no edges.

```
ubergraph.core-test=> (pprint (graph [1 1]))
Graph
1 Nodes:
         1
0 Edges:
nil
```

The same bug is true of digraphs, multigraphs, and multidigraphs as well.

**Comment by Engelberg** [comment]
Thanks.  I appreciate your reporting the bug and for providing a patch.  I hope to have time to review and push the patch in a day or two.  I usually aim to fix bugs within 24 hours, but I'm unusually busy right now.  Sorry for the delay.

**Comment by Engelberg** [comment]
Traditionally in math, a loop in an undirected graph adds two the degree, so I'm going to adjust your code accordingly.  But this is much appreciated.  Sorry it took me a while to evaluate the patch.  Will be rolling in a few other patches and deploying soon.

https://en.wikipedia.org/wiki/Loop_%28graph_theory%29#Degree

**Comment by Engelberg** [comment]
Deploying shortly as version 0.2.0.
