### ISSUE TITLE
Clojurescript?

### ISSUE THREAD

**Issue by ghost** [Engelberg/ubergraph#18]
Pardon the question that's clearly not an issue with the library:

Does this impl support clojurescript? I'm still new to the whole clojure world, and I have a hard time telling if a codebase supports both (is there an easy way to tell?)?

Thanks,
~potential user

**Comment by Engelberg** [comment]
The easy way to tell is if the file extensions are labeled cljc.  That's the indicator that the code is meant to run on both clojure and clojurescript.

Ubergraph currently has a couple dependencies on Java,  in the algorithms namespace.

The core data structure and other algorithms (or the algorithms from Loom) would work just fine under clojurescript, but it is not currently set up to do that.  As long as you're not using that particular algorithm, you could create a fork and rename the files to cljc extensions, deleting the parts that use the Java data structures.

If your needs are simple, you could look at Loom, which has placed a higher priority on ensuring that it works on both Clojure and Clojurescript.

**Comment by ghost** [comment]
Much appreciated.
