### ISSUE TITLE
What is the ubergraph? predicate for?

### ISSUE THREAD

**Issue by samestep** [Engelberg/ubergraph#25]
In `ubergraph.protocols` there is an [`IUbergraph`][iubergraph] protocol with docstring "Is it an Ubergraph?" and a single `ubergraph?` predicate. However, the only [implementation] of this protocol, for `Object`, has `ubergraph?` return false in all cases:

```clojure
(require '[ubergraph.core :as uber])

(uber/ubergraph? (uber/graph)) 
;;=> false
```

This is a bit unintuitive. What is the purpose of the `IUbergraph` protocol and its `ubergraph?` predicate?

[implementation]: https://github.com/Engelberg/ubergraph/blob/v0.3.1/src/ubergraph/core.clj#L292-L293
[iubergraph]: https://github.com/Engelberg/ubergraph/blob/v0.3.1/src/ubergraph/protocols.clj#L71-L74

**Comment by Engelberg** [comment]
Good question.  My initial plan was to make it return true for the ubergraph data structure and false for everything else (the "everything else" part is what the Object implementation is all about).  I then started thinking about the question of whether, conceptually, this predicate could return true for any structure implementing the ubergraph protocols, or whether this predicate is more useful if it only returns true if it is this concrete data structure (in which case, it shouldn't really be implemented as a protocol, but should be implemented as `(instance? Ubergraph u)`).  Mulling this over, I neglected to make a final decision and fill in the implementation.

Thank you for bringing this my attention.  I'll make a decision tonight and push a new version to clojars.  I'm leaning towards keeping it extensible for alternative implementations of ubergraph protocols, but if you have a different preferred use case, further opinions are welcome.

**Comment by samestep** [comment]
Thanks! Before trying it, I was wondering the same thing; whether it would test for the concrete implementation, or simply ask the object whether it implemented the required protocols. I'm of the opinion that the extensible option is the more useful one, but it's up to you.

**Comment by Engelberg** [comment]
Pushed as version 0.4.0
