### ISSUE TITLE
Ubergraph v0.4.0 is incompatible with loom v1.0.0

### ISSUE THREAD

**Issue by bkovitz** [Engelberg/ubergraph#26]
Ubergraph currently depends on v0.5.4 of loom, which defines protocols incompatibly with v1.0.0 of loom.

The API reference linked from [loom's github](https://github.com/aysylu/loom) is still 0.5.4, and the [documentation on Aysylu Greenberg's web site](http://aysy.lu/loom/) is still for 0.5.4, so I'm not sure it would be wise to alter ubergraph to work with the latest version of loom (is loom still actively maintained?), but I'll explain the problem anyway to save you a little time if you want to fix it.

The Graph protocol in loom v0.5.4 had a `successors` function with two arities. In loom v1.0.0, that's been replaced with `successors*`, which has only one arity. The two-arity `successors` has been moved out to a "curried wrapper" function, which does what you would reasonably expect the old `Graph/successors` function to do: the arity-2 version calls `successors*` and the arity-1 version returns a function that calls `successors*`.

A few other loom protocols have functions that have been redefined in similar ways.

**Comment by Engelberg** [comment]
Thank you for letting me know.  I had no idea that the newest version of Loom revised the protocols in an incompatible way with the old.  I'll need to do a little more research to make sure this is Loom's plan moving forward, but yes, I'd like to stay compatible with Loom.

**Comment by bkovitz** [comment]
On Oct 13, 2017, at 6:28 PM, Mark Engelberg wrote:

> Thank you for letting me know. I had no idea that the newest version of Loom revised the protocols in an incompatible way with the old. I'll need to do a little more research to make sure this is Loom's plan moving forward, but yes, I'd like to stay compatible with Loom.

Thanks for looking into it—and by the way, thanks for Ubergraph! When I first started using Clojure, I needed a library for graphs, and was fortunate to immediately find Ubergraph. In many ways, it "taught" me Clojure. I depend on Ubergraph so much, I won't upgrade to loom v1.0.0 until Ubergraph does!

Ben

**Comment by matanox** [comment]
A somewhat related pondering if you don't mind...

In a nutshell, besides it being great to have that special kind of relationship that ubergraph and loom have, what would one actually miss by using ubergraph rather than loom? what would ubergraph itself miss if it were to not depend in its code on loom?

**Comment by Engelberg** [comment]
Main advantage is that ubergraphs then can work with any of the Loom algorithms (at least in the case where you're not leveraging features of ubergraphs that Loom doesn't understand).

It's disappointing that Loom didn't comply with the "no API breakage" philosophy espoused by Clojure, and has made it a necessity to update Ubergraph, but I do intend to do it as soon as I get a chance to ask the Loom folks what's changed (or just inspect their code myself).  Sorry it has taken so long, but I've been quite busy.  Will try to get to it soon.

**Comment by matanox** [comment]
Well, thanks for making ubergraph the equivalent of what instaprase is to parsing :-)

**Comment by Engelberg** [comment]
Just deployed ubergraph 0.5.0 which is compatible with latest loom.
