### ISSUE TITLE
Small usage question about node shape

### ISSUE THREAD

**Issue by matanox** [Engelberg/ubergraph#27]
Must all nodes be keywords? or can they also be clojure vars or other clojure constructs?
I guess this question is typical of any graph API: whether node objects should be managed/defined exclusively within the API, or the API is referencing externally declared objects as its nodes. 

From the README I believe ubergraph takes the approach that all nodes should be defined within/by its API, rather than point to independently declared objects, yet I'd like to confirm this is indeed the only way of using the API.

Thanks in advance!

**Comment by Engelberg** [comment]
The nodes can be any Clojure data, atomic (e.g., keywords, numbers, strings) or compound (e.g., vectors, maps).  I can't think of any reason why you couldn't use vars as nodes.  For example, `#'a` is the var a.  If you're new to Clojure, however, make sure you understand the distinction between vars and their contents, and how equality works on vars.

**Comment by matanox** [comment]
Ooops must have been some oddity late at night, I can now see that the API indeed does accept any symbol pointing at data, not only inline data indeed. Sorry about that.
