### ISSUE TITLE
Save as dot?

### ISSUE THREAD

**Issue by devn** [Engelberg/ubergraph#31]
Am I missing something, or is there no option to save the file in graphviz dot format?

I see `:dot` as a layout, but not as a `:format`.

Thanks,
Devin

**Comment by Engelberg** [comment]
You are correct. The graphviz dot format is generated as an intermediate step on the way to building a picture. So, it's easy enough to return the graphviz dot string (or write it to a file), but it didn't occur to me that might be desirable.  Would you like a separate function that just returns the dot output as a string, or are you only interested in writing it to a file as an option in the viz-graph function?

**Comment by devn** [comment]
Hey Mark, thanks for your reply.

IIRC, the missing option for `:dot` in `viz-graph` surprised me, so I would expect it as an option there, but a separate function would also have done the trick. I dunno, kind of up to you whether you want to have a separate function to return dot, but it seems `:dot` is a natural `:format` option to include for `viz-graph`.

**Comment by Engelberg** [comment]
OK, added :dot as a :format option and pushed to github/clojars as version 0.5.1.

Also (and this has always been the case), when you save a file using viz-graph, the return value is the dot string used to generate the graph. So that's another way to get a hold of the dot information.

**Comment by devn** [comment]
Thanks!
