### ISSUE TITLE
finding all nodes in all shortest paths

### ISSUE THREAD

**Issue by lambda-ai** [Engelberg/ubergraph#32]
Hi,

first of all, sorry to abuse the ticket system to ask a question; I wasn't quite sure where else to reach you.

The shortest_path functionality is great, but I need another twist:
I understand that getting all the shortest paths is "difficult" since that explodes quickly. But for my use case I'm looking for all _nodes_ that can be part of one of the shortest paths between two nodes. Is that something that can be gotten out of your excellent library already? If not, could you give some direction for adding it (or explanation why it's not possible)?
Preferably, I would of course integrate it with the shortest_path function, so all the other functionality/variants are still there.

Thanks!
-Mathias

**Comment by Engelberg** [comment]
Call shortest-path with no specified end node.  This returns an instance of the IAllPathsFromSource protocol, let's call this result `paths`.  This is essentially a table which gives you the shortest path distance of each node in your graph from the start, and some other info such as a link to its predecessor in the search which can be used to reconstruct the shortest-path on demand.  All you care about is the distance part, which you can retrieve for a node n with: (cost-of-path (path-to paths n)).

Now, you're going to do a search back from the end node through the graph, guided by this path information.  For all predecessors p of the end node, choose p for your set if and only if `shortest path cost from start to p` + `cost from p to end` = `shortest path cost from start to end`.  For each such p, repeat this process on their predecessors, and so on until you've reached the start.  This will give you all the nodes that can be part of a shortest path.

You could either roll your own function to work backwards, or run shortest-path back from end to start in the graph with all directed edges reversed, using an :edge-filter that applies the above test to restrict the search to the relevant nodes and setting :traverse to true to get a sequence of all the nodes -- this will be your desired sequence of nodes.

**Comment by lambda-ai** [comment]
Great, thanks for the quick response!
