### ISSUE TITLE
IllegalArgumentException when requesting nodes in path

### ISSUE THREAD

**Issue by turlando** [Engelberg/ubergraph#34]
Hello there, thanks for the awesome library.

I have a bunch of nodes as such:

```clojure
> (take 5 nodes)
([558 {:stop_code      679,
       :stop_name      "SP51, 12",
       :stop_latitude  38.256900787353516,
       :stop_longitude 15.484100341796875}]
 [453 {:stop_code      574,
       :stop_name      "Via Sofia Idelson, c.da Piano dei Greci",
       :stop_latitude  38.22489929199219,
       :stop_longitude 15.547499656677246}]
 [584 {:stop_code      705,
       :stop_name      "Torrente Guardia, fer. 1",
       :stop_latitude  38.25130081176758,
       :stop_longitude 15.587499618530273}]
 [487 {:stop_code      608,
       :stop_name      "Viale Giostra, svincolo Autostrada",
       :stop_latitude  38.22100067138672,
       :stop_longitude 15.529999732971191}]
 [637 {:stop_code      758,
       :stop_name      "S. Agata, via C. Pompea n. 1647",
       :stop_latitude  38.25419998168945,
       :stop_longitude 15.600000381469727}])
```

And their relations as follows:

```clojure
> (take 5 relations)
([4 5 {:trip_id          "320755A"
       :trip_service     "FERIALE"
       :trip_destination "SAN FILIPPO SUP."
       :trip_direction   0}]
 [5 6 {:trip_id          "320755A"
       :trip_service     "FERIALE"
       :trip_destination "SAN FILIPPO SUP."
       :trip_direction   0}]
 [6 7 {:trip_id          "320755A"
       :trip_service     "FERIALE"
       :trip_destination "SAN FILIPPO SUP."
       :trip_direction   0}]
 [7 8 {:trip_id          "320755A"
       :trip_service     "FERIALE"
       :trip_destination "SAN FILIPPO SUP."
       :trip_direction   0}]
 [8 9 {:trip_id          "320755A"
       :trip_service     "FERIALE"
       :trip_destination "SAN FILIPPO SUP."
       :trip_direction   0}])

```

I then obtain the graph and I want to compute the path from node 4 to node 5:

```clojure
(def g (-> (apply ubergraph/multidigraph nodes)
           (ubergraph/add-directed-edges* relations)))
(def path (ubergraph.alg/shortest-path g {:start-node 4 :end-node 5}))
```

When I try to inspect the nodes in the path I incur in the following exception:

```clojure
> (ubergraph.alg/nodes-in-path path)
IllegalArgumentException No implementation of method: :src of protocol: #'loom.graph/Edge found for class: nil  clojure.core/-cache-protocol-fn (core_deftype.clj:583)
```

Same goes for pretty print:

```clojure
> (ubergraph.alg/pprint-path path)
Total Cost: 1
IllegalArgumentException No implementation of method: :src of protocol: #'loom.graph/Edge found for class: nil  clojure.core/-cache-protocol-fn (core_deftype.clj:583)
```

It is funny that it is able to correctly determine the path cost (I've tried with different nodes) but it will fail in showing which the nodes are.

What am I doing wrong?

Thanks for your time.

**Comment by Engelberg** [comment]
Sounds potentially like a bug. I will try to reproduce and fix it tonight.

**Comment by Engelberg** [comment]
If you have a small example, that would help me diagnose more quickly.

**Comment by Engelberg** [comment]
Also double check you are on latest version, and make sure you don't
somehow have a conflicting version of Loom, and make sure your Repl isn't
in a state where some parts of the code have been recompiled but not other
parts.

**Comment by Engelberg** [comment]
I ran some tests based on the partial data you posted in your issue.  I'm not getting any error.  So I'm starting to think it is most likely something about your project file or REPL state.

Double-check your version and make sure to try from a fresh REPL state.  If you are still having a problem, please give me data that causes the problem, and anything else about your setup that might help me narrow it down.

**Comment by Engelberg** [comment]
Also I'd be curious what you see if you just evaluate `path` at the REPL.

**Comment by turlando** [comment]
Hello again, thanks for the very fast reply.

I'm using Ubegraph 0.5.2 and I have no pinned dependency for Loom in my `project.clj`.
I think I'm using Loom 1.0.1 and there should be no other version in my system.

```
% ls .m2/repository/aysylu/loom/
1.0.1
```

I've restarted my REPL multiple times and tried both from CIDER and from plain Lein but I get the
very same exception.

This is what I get evaluating `path` right after defining it:

```clojure
#ubergraph.alg.Path{:list-of-edges #delay[{:status :pending, :val nil} 0xebb0582], :cost 1, :end 2}
```

You can try to reproduce my issue: download [this](https://github.com/turlando/metr) repo and checkout into the `graph` branch, then cd into the `backend` directory and start a REPL.

```clojure
(require '[metr.utils :as utils])
(require '[metr.graph :as graph])
(require '[ubergraph.core])
(require '[ubergraph.alg])

;; this could take some time as it needs to import the dataset
(def s (start! {:db-path            :memory
                :start-http-server? false
                :import-data?       true}))

(def dbh (:db-conn s))

(def time-min (utils/time->seconds "08:00:00"))
(def time-max (utils/time->seconds "10:00:00"))

;; trips in the time range
(def trips (db/query-trips-by-time dbh time-min time-max))

;; trip id for each trip
(def trips-ids (map :trip_id trips))

;; stops for each trip in the following format
;; [ [stops in first trips] [stops in second trip] ... ]
(def stops-in-trips (map #(db/query-stops-by-trip-id dbh % time-min time-max)
                         trips-ids))

;; flatten stops-in-trips and remove duplicates
(def all-stops (vec (reduce (fn [acc x]
                              (into acc x))
                            #{} stops-in-trips)))

;; return a list of nodes as required by ubergraph
(def nodes (graph/build-nodes :stop_id all-stops))

;; return a list in the following format:
;; [ [map-with-trip-1-info (map-with-stop-1-info map-with-stop-2-info ...)]
;;   [map-with-trip-2-info (map-with-stop-1-info map-with-stop-2-info ...)]]
(def trips-with-stops (map vector trips stops-in-trips))

;; return a list in the following format:
;; [ [ [stop-id-1 stop-id-2 {trip-1-info}]
;;     [stop-id-2 stop-id-3 {trip-1-info}] ...]
;;   [ [stop-id-5 stop-id-6 {trip-2-info}]
;;     [stop-id-6 stop-id-7 {trip-2-info}] ...]
;;  ...]
(def relations* (map #(graph/build-relations :stop_id (second %) (first %))
                     trips-with-stops))

;; Flatten relations* as required by ubergraph
(def relations (apply concat [] relations*))

;; Finally
(def g (graph/build-graph nodes relations))
(def path (ubergraph.alg/shortest-path g {:start-node 1 :end-node 2}))

(ubergraph.alg/nodes-in-path path)
IllegalArgumentException No implementation of method: :src of protocol: #'loom.graph/Edge found for class: nil  clojure.core/-cache-protocol-fn (core_deftype.clj:583)
```

Sorry for the messy code, I'm still in the experimenting phase :)

**Comment by Engelberg** [comment]
Your sample code is difficult for me to run: start! isn't in any of the required namespaces, and the db namespace alias doesn't have a corresponding require.  Even fixing these as best I could, I get an error when start! is invoked that "Address is already in use: bind".

The details of downloading the data is not relevant to the issue at hand; I just need to see what the graph data looks like.

So just give me a serialization of your graph (or better yet, a small subset of the graph that illustrates the problem):

`(uber/ubergraph->edn graph)`

`(binding [*print-dup* true] (pr-str graph))`

are two ways to serialize, both of which would potentially be interesting to me.

**Comment by turlando** [comment]
> Your sample code is difficult for me to run: start! isn't in any of the required namespaces, and the db namespace alias doesn't have a corresponding require. Even fixing these as best I could, I get an error when start! is invoked that "Address is already in use: bind".

I'm very sorry to hear that. The `start!` (and `stop!`) function is in the `metr.core` namespace
and you are supposed to run the instructions I wrote in my previous comment in such namespace.
Also double check you're on the `graph` branch and using the `backend` directory/project.

> `(uber/ubergraph->edn graph)`

[Link](
https://gist.githubusercontent.com/turlando/bfb37cf6ee43415a0ecb1c1a128522cd/raw/045d3aa8c660b856878aa1bfa56eb0dc2767474e/metr-serialization.edn) (59K)

> `(binding [*print-dup* true] (pr-str graph))`

[Link](https://gist.githubusercontent.com/turlando/b3b166ba7f9cc24082e746bac19394a2/raw/920dd7089fec480a2e99b57302b75395fe3e4cd3/metr-pr-str.edn) (234K assuming github actually allowed me to upload the whole file)

Thanks again a lot for the effort.

**Comment by Engelberg** [comment]
Here are the steps I took to try to replicate the problem:

1. I saved your edn serialization of the graph to a text file, which I called "uberbug.txt"
2. I opened the ubergraph project, compiled ubergraph.alg code in CIDER and went into the ubergraph.alg namespace in the repl.
3. `(def s (slurp "uberbug.txt"))`
4. `(def e (read-string s))`
5. `(def g (uber/edn->ubergraph e))`
6. `(def path (shortest-path g {:start-node 1 :end-node 2}))`
7. `(nodes-in-path path)`

Works as expected, returns `(1 2)`.

What do you see when you follow these steps?

**Comment by turlando** [comment]
I followed your steps and I obtained the expected result: `(1 2)`.

I tried again to define the graph, which is what I serialized from, from my routines/dataset and I still get the exception. This is pretty odd.

Could you try to obtain `nodes` and `relations` from my previous snippet again and try to compute the graph by yourself? Do you think there something wrong going on with my environment?

**Comment by Engelberg** [comment]
It does seem likely to me that it has something to do with your environment.

I'm going to have little access to a computer between now and Sunday night.  But here are some things you can try to help narrow it down:

1. In your own environment, test from serialization.  If this doesn't work, we can be pretty sure it is the environment.  As a variation, in your environment, define the graph, serialize and immediately unserialize and then test. 

2. Clone the ubergraph repo, because we know it works from there.  Gradually add your dependencies one by one and do the test from serialization, and try to identify which dependency causes it to break.

3. Ubergraph relies on potemkin, which tends to be one of the more fragile libraries in Clojure, because its implementation details change as Clojure evolves.  If I had to make a wild guess, I'd guess that maybe one of your library dependencies uses a different version of potemkin.  Maybe check this out with `lein deps :tree`

Sorry I can't be of as much help for the next few days, but hopefully this gives you some ideas to explore the problem more yourself.

**Comment by turlando** [comment]
In the last few days I took some time to inspect the bug more deeply.

I stripped down the issue to the case I'm showing below. At some point I started thinking
there was something nasty going on with the encoding of my strings (you'll see
what led me to this path) but I managed to exclude this case removing the content
of the attribute maps for nodes and edges.

---

1. **Ingredients**

A `nodes` binding:

```clojure
metr.core> nodes
([7 {}] [6 {}] [5 {}] [4 {}])
metr.core> (type nodes)
clojure.lang.LazySeq
```

A `relations` binding containing the edges:

```clojure
metr.core> relations
([4 5 {}] [5 6 {}] [6 7 {}])
metr.core> (type relations)
clojure.lang.LazySeq
```

These two bindings contain values coming from my database
which are then transformed to the shape you see.

2. **Graph and path**

I define the graph and the path as follows:

```clojure
(def g (-> (ubergraph.core/multidigraph)
           (ubergraph.core/add-nodes-with-attrs* nodes)
           (ubergraph.core/add-directed-edges* relations)))
(def path (ubergraph.alg/shortest-path g {:start-node 4 :end-node 7}))
```

3. **The exception**

```clojure
metr.core> (ubergraph.alg/nodes-in-path path)
IllegalArgumentException No implementation of method: :src of protocol: #'loom.graph/Edge found for class: nil  clojure.core/-cache-protocol-fn (core_deftype.clj:583)
```

---

We finally reproduced the bug, but did we?

1. **Ingredients**

This time I will just evaluate `nodes` and `relations` in my REPL running in CIDER
and `def` two new bindings, just copy and pasting from and to my REPL the values
I got in the first place.

```clojure
metr.core> nodes
([7 {}] [6 {}] [5 {}] [4 {}])
metr.core> (def nodes '([7 {}] [6 {}] [5 {}] [4 {}]))
#'metr.core/nodes
metr.core> (type nodes)
clojure.lang.PersistentList
```

```clojure
metr.core> relations
([4 5 {}] [5 6 {}] [6 7 {}])
metr.core> (def relations '([4 5 {}] [5 6 {}] [6 7 {}]))
#'metr.core/relations
metr.core> (type relations)
clojure.lang.PersistentList
```

2. **Graph and path**

```clojure
metr.core> (def g2 (-> (ubergraph.core/multidigraph)
      (ubergraph.core/add-nodes-with-attrs* nodes)
      (ubergraph.core/add-directed-edges* relations)))
#'metr.core/g2
```

```clojure
metr.core> (def path2 (ubergraph.alg/shortest-path g2 {:start-node 4 :end-node 7}))
#'metr.core/path2
```

Please also note that:

```clojure
metr.core> (= g g2)
true
```

3. **The exception?**

```clojure
metr.core> (ubergraph.alg/nodes-in-path path2)
(4 5 6 7)
```

No exception! (Now you should see the reason I started thinking about some strange
encoding misbehavior, but removing the map content at all made that case invalid).

---

So, maybe it could be that `LazyList`s don't work while `PersistentList`s do? Let's check:

```clojure
metr.core> (type nodes)
clojure.lang.LazySeq
metr.core> (type relations)
clojure.lang.LazySeq
```

```clojure
metr.core> (def nodes (apply list nodes))
#'metr.core/nodes
metr.core> (def relations (apply list relations))
#'metr.core/relations
metr.core> (type nodes)
clojure.lang.PersistentList
metr.core> (type relations)
clojure.lang.PersistentList
```

```clojure
metr.core> (def g3 (-> (ubergraph.core/multidigraph)
      (ubergraph.core/add-nodes-with-attrs* nodes)
      (ubergraph.core/add-directed-edges* relations)))
#'metr.core/g3
metr.core> (def path3 (ubergraph.alg/shortest-path g3 {:start-node 4 :end-node 7}))
#'metr.core/path3
metr.core> (ubergraph.alg/nodes-in-path path3)
IllegalArgumentException No implementation of method: :src of protocol: #'loom.graph/Edge found for class: nil  clojure.core/-cache-protocol-fn (core_deftype.clj:583)
```

No way!

What is going on here? I'm extremely confused...

**Comment by Engelberg** [comment]
Thanks, you've given me a lot to work with here, and I'll be able to look at it closely Sunday night or Monday.

Can you give me the specific `(def nodes ...)` and `(def relations ...)` that you're using to produce the lazy seq versions?

**Comment by Engelberg** [comment]
I've found that lazy sequences and databases don't interact well in Clojure, and I'm starting to suspect that something along these lines is your problem.  If part of the lazy seq is derived after the db connection is closed, you'd get a nil value, which could potentially explain the error message you're seeing.  Library database connections are often stored in dynamically bound variables which are especially fragile with respect to laziness.  I always wrap all queries to databases in `doall` for this very reason, unless I have a very specific reason for the laziness and know how and when it's going to be evaluated.

Try wrapping `doall` around your queries and see whether the problem goes away.  If so, the problem most likely lies in your use of the db library, and the lazy sequences are getting realized late and aren't what you think they are.

**Comment by Engelberg** [comment]
Did you have an opportunity to try wrapping `doall` around your queries?

**Comment by turlando** [comment]
Sorry for being away. I tried wrapping my `doall` around my queries and I checked that everything was `realized?`, I also tried wrapping `vec` around suff but all those things didn't solve the issue.

I wanted to show you a piece of code retrieving the data and generating the graph but I couldn't find the time. I could try to do it now if you find it meaningful/helpful.

**Comment by Engelberg** [comment]
I'm having a hard time imagining how it could be a problem with ubergraph, but if it is, I want to know about it.  So if you have further info about the data that's causing problems, I'm interested.

**Comment by turlando** [comment]
Thanks a lot for the support. I'll get back to you as soon as possible.

**Comment by samirsa** [comment]
Thanks for a very useful library!

To update this issue, in case someone lands here (like I did) or maybe you think this can be fixed in ubergraph's code, here is what I found.

I followed some of the debug mechanisms you suggested here, in terms of ```ubergraph->edn``` and the ```pr-str``` to identify differences between the graph generated by my code and a topologically equivalent graph. It seemed that the only difference was that the edges generated by my code were integers, whereas if I were to add them via direct code, they are taken as long. (the ```pr-str``` seemed to have a lot of explicit code for some kind of checks or something for java.lang.Integer). 

Typecasting my edges as long seems to have solved this issue for now, but I think this is something which should possibly be fixed in ubergraph?

Here are some trivial examples, one of which generates an exception and the other doesnt

```clojure
(-> (u/digraph)
    (u/add-nodes 1 2 3 4)
    (u/add-edges [(int 1) (int 2)] [(int 2) (int 3)] [(int 3) (int 4)])
    (ua/shortest-path 1 4)
    (ua/nodes-in-path))

(-> (u/digraph)
    (u/add-nodes 1 2 3 4)
    (u/add-edges [(long 1) (long 2)] [(long 2) (long 3)] [(long 3) (long 4)])
    (ua/shortest-path 1 4)
    (ua/pprint-path))
```

**Comment by Engelberg** [comment]
The `shortest-path` algorithm uses Java data structures for maximum speed. Unfortunately, Java doesn't consider longs and ints to be equal, while Clojure does consider them to be equal. If you use longs for your nodes, and ints for your edges, Clojure will treat them as the same, which works for almost everything in ubergraph except the shortest-path algorithm. This is usually a non-issue because Clojure defaults to creating longs, so it is uncommon to end up with a mixture of ints and longs in your code. 

One way to solve the problem would be for me to avoid using Java data structures in the `shortest-path` algorithm, which would also have the benefit of making that algorithm clojurescript-compatible. However, the speed of `shortest-path` is a top priority to me, because it's one of my primary uses for Ubergraph, so I'm reluctant to shift away from using Java data structures. I think the better solution is to be clearer in the documentation that being inconsistent in using longs and ints could cause problems with `shortest-path`. Then, you have the option to typecast the ints to longs (like you did), or to use related algorithms from loom (e.g., `astar-path`), which don't utilize Java, and work on Ubergraphs (because Ubergraphs are designed to be loom-compatible).
