### ISSUE TITLE
Perhaps more escaping help for ubergraph users?

### ISSUE THREAD

**Issue by jafingerhut** [Engelberg/ubergraph#36]
First of all, thanks for developing ubergraph.  I had heard of both loom and ubergraph before, but had not looked into either one carefully before, and recently found a use case and was very glad that ubergraph handled multiple parallel edges out of the box, since I needed that.  A pleasure to use.  Reminds me of a time in early 1990s when I was a grad student, and wished for something like this, e.g. a system representing graphs with arbitrary sets of node and edge attributes, and a collection of useful algorithms that work on them all.  It is certainly here now.

I was getting deep into the bowels of what characters are supported in Graphviz node and edge labels, because I wanted to include Clojure values converted to strings via clojure.core/str in such labels, and found a few cases that rhizome handled that ubergraph does not, and wanted to ask whether you were interested in anything like the following as additions to ubergraph?

(a) when `:auto-label true` is specified, handle more of these cases cleanly
(b) when `:auto-label true` is not specified, provide a little utility function to the user that is documented as helping them escape the characters needed to avoid errors in dot files.

**Comment by Engelberg** [comment]
Yes I would be interested in this as long as it does not require a dependency on rhizome. Thanks for your interest in ubergraph.
