### ISSUE TITLE
Should removing a node from a graph also remove its attributes?

### ISSUE THREAD

**Issue by jafingerhut** [Engelberg/ubergraph#38]
With ubergraph 0.5.3, removing a node leaves behind the attributes of that nodes in the attrs field of the returned graph value.

Thus if you take such a graph and later add the same node back in, it will have the attributes it had before.

Here is a reproduction of a sequence of calls demonstrating the current behavior:
```
(require '[ubergraph.core :as uber])
(def g1 (uber/multidigraph [1 {:label "n1"}]
                           [2 {:label "n2"}]
                           [1 2 {:label "edge12"}]))
(uber/pprint g1)
;; node 2 has attributes {:label "n2"} as expected

(def g2 (uber/remove-nodes g1 2))
(uber/pprint g2)
;; node 2 not in g2, as expected

(def g3 (uber/add-nodes g2 2))
(uber/pprint g3)
;; node 2 is in g3, as expected, but with attributes {:label "n2"}.  Expected?
;; root cause is that function ubergraph.core/remove-node does not dissoc the node
;; from the attrs map.
```

**Comment by Engelberg** [comment]
Thanks for pointing this out. I consider this a bug.

**Comment by Engelberg** [comment]
I'm busy this week due to the holiday, but can look at it next week.

**Comment by jafingerhut** [comment]
Created a proposed PR that I believe fixes the issue, and adds a test case that fails without the fix, and works with it, based upon the example sequence above. https://github.com/Engelberg/ubergraph/pull/39

Oh, and no rush on my part to look at this.  Just wanted to create the PR while I was thinking about it.

**Comment by Engelberg** [comment]
Is there a similar problem with edge attributes sticking around after edge or one of the nodes is deleted?

**Comment by jafingerhut** [comment]
I do not think so, but will verify, and can add a test case for this to the proposed PR.

I discovered this problem by reading some of the code to see how attributes work, then creating the test case to confirm that it was misbehaving.  The remove-edge function appears to be doing the correct :attrs adjustments.
