### ISSUE TITLE
Questions for possible mention in ubergraph docs somewhere

### ISSUE THREAD

**Issue by jafingerhut** [Engelberg/ubergraph#40]
Maybe they are already mentioned and I didn't read that part of the docs.

I believe that if one wanted to state a rule for "what values can I use as an ubergraph node?", one correct answer would be "any immutable Clojure value, that has correct behavior for clojure.core/= and clojure.core/hash, e.g. numbers, characters, strings, booleans, lists, vectors, sets, maps, queues, ..."  Not sure about whether nil would be handled cleanly.

One exception to this, I think, is that an edge value should _not_ be used as a node.  Maybe obvious, but I could imagine some kind of dual graph algorithms that swap nodes and edges around where someone might try it and be thwarted by some implementation issues.

Unlike nodes, edges are not values the caller provides, but ones that ubergraph creates for you.

It also seems mentioning explicitly somewhere that node and edge attributes are properties of the graph as a whole, i.e. you can take a value like 5 and add it as a node in two different graphs, but their attributes in those two graphs are independent of each other.

Is it an error to try to take an edge from one graph and add it to another?  I can look into the implementation to find out.

**Comment by jafingerhut** [comment]
In case you are worried, I am pretty certain the rate of issue creation will taper off pretty quickly here.  I've just been using ubergraph for the first time in the last week quite a bit, and wanted to mention questions I asked myself during that time.

**Comment by jafingerhut** [comment]
Another thing I personally may dig into in hopes of adding a few notes on.  I know you have a section on equality of graphs in the README, but I'd like to see a little bit more.  e.g. are two ubergraphs equal only if their sets of nodes clojure.core/= to each other?  And the edges are somehow equal between "corresponding nodes", where nodes only correspond if they are clojure.core/= to each other?  That would make a whole lot more sense than implementing a very computationally expensive graph isomorphism algorithm for equality of ubergraphs, but even there it makes me wonder what happens if both graphs have 70,000 parallel edges between nodes 1 and 2.

Are attributes involved in comparisons between ubergraphs for =, or ignored?

**Comment by Engelberg** [comment]
I'd have to double-check the source, but I'm fairly sure attributes are
involved in equality comparison.

Equality of nodes is straightforward.  Edge equality is more complicated
because two equal graphs created at different times will have different
edge uuids, so we check that ignoring those ids we have the same semantic
edge relationships between nodes (and attributes on those edges, I think).

**Comment by jafingerhut** [comment]
Yes, I looked at ubergraph.core/equal-graphs? and equal-edges? and was pleasantly surprised by how thorough you were in equal-edges? at handling parallel edges with attributes.  Cool.

**Comment by jafingerhut** [comment]
Notes from a little more investigation:

Ubergraph's API does not allow you to take an `Edge` or `UndirectedEdge` object found via `find-edge` and add it as an edge to a different graph (I will say only `Edge` from now on -- but think `Edge` or `UndirectedEdge`).  All APIs for adding edges to a graph require a pair of nodes somewhere, never an `Edge` object.  That seems like a good thing to me, as it prevents accidentally taking an `Edge` from one graph and adding it to another, or even of adding an `Edge` from a graph to that same graph again.  I have found no problems in that area -- I just wanted to mention it.

There is nothing in the API or implementation that stops you from taking an `Edge` object found via `find-edge` and adding it as a _node_ to the same or a different graph.  This appears not to be supported, though, as it does not track attributes correctly after doing that.  I cannot think of any strong reason to attempt to support such an odd use case myself, and at the very least it seems worth documenting "don't do that -- it is not supported".  Perhaps it is worth considering whether there should be an exception thrown if you attempt to do so.

Below is an example REPL session showing how attributes can go wrong if you try this.  Check out the attribute on edge `1 -> 2` in graph `g2` at the end:
```
user=> (require '[ubergraph.core :as uber])
nil
(def g1 (uber/multidigraph [1 {:label "n1"}]
                           [2 {:label "n2"}]
                           [1 2 {:label "edge12"}]))
#'user/g1
user=> (uber/pprint g1)
Multidigraph
2 Nodes:
	 1 {:label n1}
	 2 {:label n2}
1 Edges:
	 1 -> 2 {:label edge12}
nil
user=> (def edge-from-g1 (uber/find-edge g1 1 2))
#'user/edge-from-g1
user=> edge-from-g1
#ubergraph.core.Edge{:id #uuid "57017dfe-fbdc-4c67-ac72-27c29a2e2996", :src 1, :dest 2}
user=> (def g2 (uber/add-nodes-with-attrs g1 [edge-from-g1 {:label "node-weird"}]))
#'user/g2
user=> (uber/pprint g2)
Multidigraph
3 Nodes:
	 1 {:label n1}
	 2 {:label n2}
	 #ubergraph.core.Edge{:id #uuid "57017dfe-fbdc-4c67-ac72-27c29a2e2996", :src 1, :dest 2} {:label node-weird}
1 Edges:
	 1 -> 2 {:label node-weird}
```

**Comment by jafingerhut** [comment]
Created this PR that adds comments explaining most or all of the things above: https://github.com/Engelberg/ubergraph/pull/41

If you think that it would be good to throw an exception when someone attempts to add a value for which `edge?` returns true as a node, I can create a proposed PR for that.

**Comment by Engelberg** [comment]
This comment from your notes is not entirely accurate: "The methods for adding edges to a graph do not take an edge object directly, only pairs of nodes, plus optional attributes, so there is no way to add an edge object from one graph to another." The build-graph function does allow you to pass an edge object directly (and whole other ubergraph objects, for that matter), but it is smart about stripping out the uuids and assigning fresh ones. If I remember correctly, add-edges also is smart about taking Edge objects. I will edit accordingly.

**Comment by Engelberg** [comment]
Glad I investigated this. build-graph was doing the right thing with other Edge objects, but add-edges was only copying over the weight attribute. But in both cases, new UUIDs were being created as I expected. Now fixed.

**Comment by Engelberg** [comment]
Upon further thought, I think I'm going to just disallow Edge objects from add-edges, because the whole point of add-edges is to "do the right thing" with an edge description and the default directedness/undirectedness of the graph, and if an Edge object rather than an edge description is passed in, it's not at all obvious whether users would prefer the directedness of the Edge or the directedness of the graph. The reason it sort of worked before is because if you passed in an Edge to add-edges, it automatically gets destructured as [src dest weight], so you get a very simplistic "edge description" out of the edge object. But this could be confusing, so I'm going to throw an error now and direct people to use build-graph instead if they want to add Edge objects since it has explicit handling for that which maintains directedness of the edges regardless of overall type of graph. I'll continue to allow add-directed-edges and add-undirected-edges to take Edge objects, extracting [src dest attributes] from the Edge as its edge description.
