### ISSUE TITLE
Add full support for namespaced keywords

### ISSUE THREAD

**Issue by thenonameguy** [Engelberg/ubergraph#42]
The viz-graph function does not correctly display the full stringified version of the keyword, losing information in the process. If there are other cases where `name` is used on keywords, those should be updated to just use `str` instead.

**Comment by Engelberg** [comment]
Would this pull request address your concern? https://github.com/Engelberg/ubergraph/pull/37

I'll likely be merging it this week.

**Comment by jafingerhut** [comment]
Given the description, if @thenonameguy is using `:auto-label true` as an option to `viz-graph`, then that PR will not change what they are asking about.

I think it is this line of code they are referring to: https://github.com/Engelberg/ubergraph/blob/master/src/ubergraph/core.clj#L828

and they are hoping that the expression `(if (keyword? n) (name n) n)` would instead be merely `n`.  That would also cause a slight change in behavior where the colon would now appear before all keywords, whether they had namespaces or not.

**Comment by Engelberg** [comment]
In my own experience, using `name` on keywords makes the visualization far more readable, far less cluttered. Aside from the `:` character, are there other formatting issues that make `name` a problem for you?

**Comment by thenonameguy** [comment]
@jafingerhut thanks, you are correct.
@Engelberg My use case is that I use the namespace feature as a "pseudo-attr" for my nodes.
`:node-type-1/foo` `:node-type-2/foo`, etc.
Since the namespace part is dropped via the `name` fn the nodes are indistinguishable in viz-graph.
I would propose to use: `(subs (str n) 1)` in place of `(name n)` so that the colon is dropped. This way no breaking change is introduced and my use case is fulfilled.

**Comment by Engelberg** [comment]
That sounds reasonable to me.
