### ISSUE TITLE
find-edges returns edges with no metadata

### ISSUE THREAD

**Issue by jafingerhut** [Engelberg/ubergraph#46]
It seems that returning metadata on edges is done for edges, in-edges, and out-edges, identifying the graph that the edge came from, and this is used in a few functions to look up the edge in that graph.

**Comment by jafingerhut** [comment]
I can propose a PR for this, if you think it is a problem.

**Comment by Engelberg** [comment]
Yes it is a problem. Thanks.

**Comment by Engelberg** [comment]
Current plan is not to fix. See pull request for discussion.

**Comment by jafingerhut** [comment]
For my ease of reference, that pull request is https://github.com/Engelberg/ubergraph/pull/49

And the reasons for not fixing seem perfectly fine to me.  Thanks for thinking on the best way forward.
