### ISSUE TITLE
Possible warning for documentation on attribute functions

### ISSUE THREAD

**Issue by jafingerhut** [Engelberg/ubergraph#50]
If you have a graph where:

* some nodes are vectors of 2 elements (maybe also other lengths?), and some are just the elements, and
* you want to have attributes on nodes and/or edges

it is probably safest to always use the arities of those functions where the source and dest node are given as separate args, or pass edges as edge objects x for which (edge? x) is true.

Otherwise, you could easily get into situations where you think you are setting an attribute on a node, but end up setting one on an edge instead, if the node doesn't exist, because of the way resolve-node-or-edge falls back to trying to find an edge at the end.

**Comment by Engelberg** [comment]
I have included a warning to only manipulate attributes on nodes and edges that you know to exist.
