### ISSUE TITLE
`topsort` doesn't work with multigraphs

### ISSUE THREAD

**Issue by dpetranek** [Engelberg/ubergraph#59]
Loom's `topsort` algorithm does not work with multigraphs.

I've transformed the sequence `[1 2 1]` into a multiset of observed-before tuples: `[1 2] [1 1] [2 1]`, where the first element appears before the second element (1 appears before both 1 and 2, 2 appears before 1).

I can build a multigraph easily enough: `(uber/multidigraph [1 2] [1 1] [2 1])`.
```
Multidigraph
2 Nodes:
	 1 
	 2 
3 Edges:
	 1 -> 2 
	 1 -> 1 
	 2 -> 1 
```

However, when I topologically sort it, it just returns `nil`:

`(alg/topsort (graph/multidigraph [1 1] [1 1])) ;; => nil`

Presumably it is using value equality checking to detect cycles, and giving up.

I would expect the topological sort output to be `(1 2 1)`.

**Comment by dpetranek** [comment]
I'm going to take a stab at fixing this, but any pointers are appreciated. I think I would just move the implementation into `ubergraph.alg` since Loom doesn't handle multigraphs.

It would also be nice if `topsort` took a comparator function to break ties and return a consistent ordering, so I'll see if that's feasible as well.

**Comment by Engelberg** [comment]
Topological sort is only defined for acyclic graphs. I believe topsort does work on multigraphs, but you are applying it to a graph with a cycle, so nil would be the expected output. Why are you expecting the output to be (1 2 1)?

https://en.wikipedia.org/wiki/Topological_sorting

**Comment by dpetranek** [comment]
I was expecting topsort to be checking node ids for cycles, not node values.

In my example, it's more accurate to say that the edges are `[1 2] [1 1'] [2 1']`, which doesn't have any cycles and should sort to `(1 2 1')` However, I see now that the edge `[1 1]` is interpreted as a self-directed edge. Which makes sense - 1 is given the same id every time it the graph sees it. I either need bespoke equality checking or mapping values to something unique.

In any case, it looks like ubergraph is doing what it is supposed to and I'll have to figure out a different approach.

**Comment by Engelberg** [comment]
It sounds like what you want is to give each of those nodes distinct ids (e.g., increasing numbers, or gensyms) and then add these values as attributes of the node.

Another possible approach would be to make the nodes (atom 1) (atom 2) (atom 1). That would make the nodes distinct since two atoms are only equal if they are identical, regardless of whether they have the same contents.

**Comment by Engelberg** [comment]
I guess the key is to realize that whatever value you use to specify the node IS the id.
