### ISSUE TITLE
Adding metadata produces wrong graph

### ISSUE THREAD

**Issue by simongray** [Engelberg/ubergraph#60]
_Don't mind all the empty attribute maps below. My actual data does have attributes - and uses integers as ids - but I saw no reason to include them in the example code._

---

Constructing a directed graph from basic init data produces a graph with 3 nodes and 2 edges between them (as expected):

```clojure
(-> (uber/digraph [:a {}]
                  [:b {}]
                  [:c {}]
                  [:a :b {}]
                  [:b :c {}])
    (uber/pprint))
```

```
Digraph
3 Nodes:
	 :a 
	 :b 
	 :c 
2 Edges:
	 :a -> :b 
	 :b -> :c 
```

----

However, adding explanatory metadata, which is supposed to help the graph construction algorithm, produces a graph with 6 nodes instead? I would expect the addition of metadata to aid in the construction of the graph, not confuse the graph construction algorithm.

```clojure
(-> (uber/digraph ^:node [:a {}]
                  ^:node [:b {}]
                  ^:node [:c {}]
                  ^:edge [:a :b {}]
                  ^:edge [:b :c {}])
    (uber/pprint))
```

```
Digraph
6 Nodes:
	 [:a {}] 
	 [:b {}] 
	 [:c {}] 
	 :a 
	 :b 
	 :c 
2 Edges:
	 :a -> :b 
	 :b -> :c 
```

**Comment by Engelberg** [comment]
`^:node` metadata specifically says that the thing following it is a node.
So in your example, you are changing ubergraph from its natural interpretation that `[:a {}]` is a node `:a` with attribute map `{}`, and forcing it instead to interpret it as a node whose name is `[:a {}]`.

You would want to use `^:node` in a context where your node names have the form of a node with attributes or an edge or an edge with attributes, and you want to be totally clear you are talking about a node.

Alternatively, if you want to remove any ambiguity, create an empty ubergraph and use `add-nodes`, `add-nodes-with-attrs`, or `add-edges` functions.

**Comment by Engelberg** [comment]
One possible area of confusion is that it is easy for ubergraph to discriminate between a simple edge description with no attributes and an edge description that has a weight and an edge description that has an attribute map, so `^:edge` metadata can be used for all of those scenarios.

On the other hand, there is no easy way for ubergraph to determine with certainty whether `[:a {}]` is a node with the name `[:a {}]` or a node with the name `:a` and attribute map `{}`. It assumes the latter, unless you use the `^:node` metadata, which forces it to treat the entire thing as the name of the node.

So `^:node` really means to treat it as a node. You could use something like `^:node-with-attrs` as your markup in your example, if you feel you need it to improve the readability of your code. There is no special handling in ubergraph for that particular metadata tag, but as long as it's not marked with `^:node` or `^:edge` it will correctly deduce that you are describing a node with an attribute map.

**Comment by Engelberg** [comment]
The basic logic is to consider things in this order:
If it is marked with a `^:node`, treat it as the name of the node, if it is marked with an `^:edge`, treat it as some sort of edge description.
If it looks like an adjacency map, treat it as such.
If it looks like a node with attributes, treat it as such.
If it looks like an edge, treat it as such.
Otherwise, it's a node name.

You can see that `^:node` and `^:edge` are used to lift the two cases that generally come last in the logic sequence, bumping them to top priority in the case where you have nodes or edges that look like other things (so, for example, nodes that are maps or vectors of length 2 or 3 rather than simple things like keywords or numbers.

Nodes with attributes don't require annotation to be handled correctly.

**Comment by simongray** [comment]
> On the other hand, there is no easy way for ubergraph to determine with certainty whether [:a {}] is a node with the name [:a {}] or a node with the name :a and attribute map {}. It assumes the latter, unless you use the ^:node metadata, which forces it to treat the entire thing as the name of the node.

I see. Thank you for explaining this to me 👍 

The section about this in the README talks about labeled nodes, which I now see - with your explanation - refers treating the entire vector _as a label_. It wasn't really clear to me before, though, and I even re-read that part quite a few times :P 

> It is often convenient that the ubergraph constructors can take so many different kinds of "inits", but as you can see, there is some inherent ambiguity. Should we interpret [{:a 1} {:b 2}] as a node labeled [{:a 1} {:b 2}], or as a node {:a 1} with attribute map {:b 2}, or as an edge between two nodes {:a 1} and {:b 2}? In this particular case, Ubergraph would interpret the ambiguous init as a [node attribute-map] form (resolution of conflicts is in the order listed above), but you can force the other interpretations by adding ^:node or ^:edge metadata, i.e., _**^:node [{:a 1} {:b 2}] would be interpreted as a node labeled [{:a 1} {:b 2}]**_ and ^:edge [{:a 1} {:b 2}] would be interpreted as an edge between two nodes. Alternatively, you can construct an empty ubergraph and build it up with the unambiguous functions add-nodes, add-nodes-with-attrs, or add-edges.

Thanks for making ubergraph. I'm integrating it with Neo4j at the moment.
