### ISSUE TITLE
In Dorothy 0.0.7, save! moved to dorothy.jvm

### ISSUE THREAD

**Issue by claj** [Engelberg/ubergraph#63]
Using Dorothy 0.0.7 gives a compilation error when requiring `ubergraph.core` doing

```
(require '[ubergraph.core :as uber])
Syntax error compiling at (ubergraph/core.clj:963:44).
No such var: d/save!
```

A project.clj to reproduce is

```
(defproject gruber "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.11.1"]
                 [ubergraph "0.8.2"]
                 [dorothy "0.0.7"]]
  :repl-options {:init-ns gruber.core})

```

In dorothy 0.0.7 `save!` (as well as some other functions) has moved to the namespace `dorothy.jvm`, and the [Readme](https://github.com/daveray/dorothy#render-images-via-graphviz-clojurejvm) is updated to reflect this.

**Comment by aeonik** [comment]
@claj,
I don't have a pull request for @Engelberg yet, though it looks like he has been pretty busy with other things.

For now, I have forked the repo, and added your fix here:

https://github.com/aeonik/ubergraph/

You can use this directly via git coordinates in your deps.end like the following:
``` edn
ubergraph/ubergraph              {:git/url "https://github.com/aeonik/ubergraph.git"
                                  :sha     "8abd3c9f3a5e4925375895b38fa274742f41b097"}
```

Changelog is here:
https://github.com/Engelberg/ubergraph/compare/master...aeonik:ubergraph:master

Regards,
Aeonik

**Comment by Engelberg** [comment]
Fixed.
