### ISSUE TITLE
Functions taking edge descriptions can't deal with multigraphs and multi-digraphs

### ISSUE THREAD

**Issue by dgr** [Engelberg/ubergraph#67]
Many Ubergraph functions such as `weight` and `attr` take a "edge description" rather than an edge object. An edge description is ambiguous in the case of parallel edges in a multigraph or multi-digraph. Sometimes, adding a weight to an edge description helps a function disambiguate between parallel edges, but this is inconsistent. In particular, it's silly to add a weight when you're trying to get the weight.

```clojure
user> (require '[ubergraph.core :as graph])
nil
user> (def foo (graph/multigraph [0 1 1] [0 1 2] [0 1 3]))
#'user/foo
user> (graph/weight foo [0 1])
1
user> (graph/attrs foo [0 1])
{:weight 1}
user> (graph/weight foo [0 1 3])
1   ;; THIS IS WRONG
user> (graph/attrs foo [0 1 3])
{:weight 3}
```

This is with Ubergraph 0.8.2.

**Comment by Engelberg** [comment]
Fixed
