### ISSUE TITLE
Function ubergraph.core/weight doesn't return the correct weight for parallel edge specified with edge objects in multigraph/multi-digraph 

### ISSUE THREAD

**Issue by dgr** [Engelberg/ubergraph#68]
Functions can take an edge object (e.g., `ubergraph.core.UndirectedEdge`), but there appear to be bugs there, too:

```clojure
user> (require '[ubergraph.core :as graph])
nil
user> (def foo (graph/multigraph [0 1 1] [0 1 2] [0 1 3]))
#'user/foo
user> (graph/edges foo)
({:id #uuid "f24c94aa-45cc-40a4-b6ed-2e59e3bf58a9",
  :src 0,
  :dest 1,
  :mirror? false}
 {:id #uuid "f80e1cb2-803e-47ba-826d-def60cb407b2",
  :src 0,
  :dest 1,
  :mirror? false}
 {:id #uuid "8e38813a-1412-4387-882e-b1a5a8487eba",
  :src 0,
  :dest 1,
  :mirror? false}
 {:id #uuid "f80e1cb2-803e-47ba-826d-def60cb407b2",
  :src 1,
  :dest 0,
  :mirror? true}
 {:id #uuid "f24c94aa-45cc-40a4-b6ed-2e59e3bf58a9",
  :src 1,
  :dest 0,
  :mirror? true}
 {:id #uuid "8e38813a-1412-4387-882e-b1a5a8487eba",
  :src 1,
  :dest 0,
  :mirror? true})
user> (class (first *1))
ubergraph.core.UndirectedEdge
user> (map #(graph/weight foo %) (graph/edges foo))
(1 1 1 2 2 2)  ;; this is wrong
user> (map #(graph/attr foo % :weight) (graph/edges foo))
(1 2 3 2 1 3)  ;; correct, ignoring the fact that graph/edges returns mirror edges
```

This is with Ubergraph 0.8.2.

**Comment by Engelberg** [comment]
That looks like a bug in loom's implementation of weight as (weight edge)
should simply call (weight* edge). They aren't respecting their own
protocol. Not sure why no one ever caught that before. Good catch!

In theory, it should be fixed in loom. But in the meantime, it should
probably just be implemented correctly in Ubergraph.

I'm away from a computer for the next two weeks, but will fix this ASAP.

**Comment by Engelberg** [comment]
In the meantime, you could use weight* instead of weight.

**Comment by Engelberg** [comment]
The idea here is that graph implementations are supposed to implement
weight* protocol func and then weight is just a convenience function that
calls the underlying protocol function. But loom is dispatching the edge
arity to weight*'s node arity, so the protocol implementation for edges is
never getting called.

**Comment by Engelberg** [comment]
Fixed.
