### ISSUE TITLE
Reflection warning in `nodes` method

### ISSUE THREAD

**Issue by stephenbrady** [Engelberg/ubergraph#8]
`.keySet` is a `java.util.Map` method so the type hint to `IPersistentMap` is generating a reflection warning.

https://github.com/Engelberg/ubergraph/blob/master/src/ubergraph/core.clj#L122

**Comment by Engelberg** [comment]
Thanks for reporting.  Will try to push an update soon.

**Comment by Engelberg** [comment]
Fixed in 0.1.8
